document.write("<section class='head'>");
document.write("<h1>HEADER</h1>");
document.write("</section>");
document.write("<div class='box'>");
document.write("<section class='nav'>");
document.write("<h2>NAVEGATION</h2>");
document.write("</section>");
document.write("<section class='art1'>");
document.write("<h3>ARTICLE 1</h3>");
document.write("</section>");
document.write("<section class='art2'>");
document.write("<h3>ARTICLE 2</h3>");
document.write("</section>");
document.write("<section class='art3'>");
document.write("<h3>ARTICLE 3</h3>");
document.write("</section>");
document.write("</div>");
document.write("<section class='footer'>");
document.write("<h1>FOOTER</h1>");
document.write("<i class='fas fa-arrow-left'></i><a href='../dashboard.html'>REGRESAR <a>");
document.write("</section>");